### PR TITLE
Return conn instead of chan from `connection` fun

### PR DESCRIPTION
**Pull request by mfalt**
Might break some code that depends on this incorrect behavior.

### CODE REVIEW

**Comment by tanmaykm** [comment]
Thanks, this does seem correct.
Just want to walk through the code once to check if anything else is impacted before merging.

**Comment by nsslh** [comment]
I am anxious about the impact of this change on existing code that passes the return value of `connection` into `channel`.

```
conn = connection(; ...)
chan = channel(conn, AMQPClient.UNUSED_CHANNEL, true)
basic_qos(chan, 0, 1, false; timeout = 10)
success, queue_name, ... = queue_declare(...)
... = basic_consume(chan, queue_name, msg -> consume_fn(chan, msg, routes))
fetch(chan.consumers[consumer_tag].receiver)
```

**Comment by mfalt** [comment]
I think this specific case won't be a problem since the channel function seems to have been implemented to handle both `connection` and `channel``as input:
https://github.com/JuliaComputing/AMQPClient.jl/blob/3f004562040d4ba773fb1e0a94f69e6ebe296758/src/protocol.jl#L537
It would however break code like this:
```julia
conn = connection(; ...)
chan = channel(chan.conn, AMQPClient.UNUSED_CHANNEL, true)
```
So I think it warrants a bump to 0.5

**Comment by nsslh** [comment]
> So I think it warrants a bump to 0.5

If AMQPClient is using semantic versioning, then 1.0.0 is probably a safer choice, since it's a breaking change (for some).

**Comment by mfalt** [comment]
Semver doesn't require any compability for releases before 1.0.0, but Julia
specifies that the minor version should be updated for breaking changes pre
1.0
https://pkgdocs.julialang.org/v1/compatibility/#compat-pre-1.0

**Comment by nsslh** [comment]
> Semver doesn't require any compability for releases before 1.0.0

I had never noticed that. Thanks!

**Comment by nsslh** [comment]
Fixes #51

**Pull request merged**
